### ISSUE TITLE
一个小疑问

### ISSUE THREAD

**Issue by perfchen** [qinci/EdgeTranslucent#3]
今天做一个类似功能，有幸看到了这个库，不太理解绘制边缘渐变时为什么要旋转保存图层。感觉可以给画笔设置不同的渐变方向，直接绘制四个矩形，这样应该可以节省一些开销吧。

**Comment by qinci** [comment]
其实你多虑了、旋转操作是一个状态！
你更应该考虑的是图层隔离的开销！

**Comment by perfchen** [comment]
感谢回复！我表述的不太明白，意思是直接在原始图层上绘制矩形就可以了，没必要在新的图层上绘制

**Comment by qinci** [comment]
你可以试试哈，代码里面隔离图层不是为了旋转操作而保存的，而直接绘制的话 不会是透明效果~
旋转操作只是为了方便做的处理。

**Comment by qinci** [comment]
如果你的需求不需要看到背景的东西（比如背景是白色的，那么直接画一个白色渐变效率是最高的）

**Comment by Mark1Chen** [comment]
`@Override
    protected boolean drawChild(Canvas canvas, View child, long drawingTime) {
        boolean drawChild = super.drawChild(canvas, child, drawingTime);
        if (topTransHeight > 0) {
            mPaint.setShader(new LinearGradient(0, 0, 0, topTransHeight, mGradientColors, mGradientPosition,
                    Shader.TileMode.CLAMP));
            canvas.drawRect(0, 0, mWidth, topTransHeight, mPaint);
        }

        if (bottomTransHeight > 0) {
            // 底部上边缘位置
            float bottomTop = mHeight - bottomTransHeight;
            bottomTop = bottomTop > 0 ? bottomTop : 0;
            mPaint.setShader(new LinearGradient(0, mHeight, 0, bottomTop, mGradientColors,
                    mGradientPosition, Shader.TileMode.CLAMP));
            canvas.drawRect(0, bottomTop, mWidth, mHeight, mPaint);
        }

        if (leftTransWidth > 0) {
            mPaint.setShader(new LinearGradient(0, 0, leftTransWidth, 0, mGradientColors, mGradientPosition,
                    Shader.TileMode.CLAMP));
            canvas.drawRect(0, 0, leftTransWidth, mHeight, mPaint);
        }

        if (rightTransWidth > 0) {
            // 右侧左边缘位置
            float rightLeft = mWidth - rightTransWidth;
            rightLeft = rightLeft > 0 ? rightLeft : 0;

            mPaint.setShader(new LinearGradient(mWidth, 0, rightLeft, 0, mGradientColors, mGradientPosition,
                    Shader.TileMode.CLAMP));
            canvas.drawRect(rightLeft, 0, mWidth, mHeight, mPaint);
        }
        return drawChild;
    }`

**Comment by Mark1Chen** [comment]
`@Override
    protected boolean drawChild(Canvas canvas, View child, long drawingTime) {
        boolean drawChild = super.drawChild(canvas, child, drawingTime);
        if (topTransHeight > 0) {
            mPaint.setShader(new LinearGradient(0, 0, 0, topTransHeight, mGradientColors, mGradientPosition,
                    Shader.TileMode.CLAMP));
            canvas.drawRect(0, 0, mWidth, topTransHeight, mPaint);
        }

        if (bottomTransHeight > 0) {
            // 底部上边缘位置
            float bottomTop = mHeight - bottomTransHeight;
            bottomTop = bottomTop > 0 ? bottomTop : 0;
            mPaint.setShader(new LinearGradient(0, mHeight, 0, bottomTop, mGradientColors,
                    mGradientPosition, Shader.TileMode.CLAMP));
            canvas.drawRect(0, bottomTop, mWidth, mHeight, mPaint);
        }

        if (leftTransWidth > 0) {
            mPaint.setShader(new LinearGradient(0, 0, leftTransWidth, 0, mGradientColors, mGradientPosition,
                    Shader.TileMode.CLAMP));
            canvas.drawRect(0, 0, leftTransWidth, mHeight, mPaint);
        }

        if (rightTransWidth > 0) {
            // 右侧左边缘位置
            float rightLeft = mWidth - rightTransWidth;
            rightLeft = rightLeft > 0 ? rightLeft : 0;

            mPaint.setShader(new LinearGradient(mWidth, 0, rightLeft, 0, mGradientColors, mGradientPosition,
                    Shader.TileMode.CLAMP));
            canvas.drawRect(rightLeft, 0, mWidth, mHeight, mPaint);
        }
        return drawChild;
    }`

**Comment by perfchen** [comment]
@Override
    protected boolean drawChild(Canvas canvas, View child, long drawingTime) {
        boolean drawChild = super.drawChild(canvas, child, drawingTime);
        if (topTransHeight > 0) {
            mPaint.setShader(new LinearGradient(0, 0, 0, topTransHeight, mGradientColors, mGradientPosition,
                    Shader.TileMode.CLAMP));
            canvas.drawRect(0, 0, mWidth, topTransHeight, mPaint);
        }

        if (bottomTransHeight > 0) {
            // 底部上边缘位置
            float bottomTop = mHeight - bottomTransHeight;
            bottomTop = bottomTop > 0 ? bottomTop : 0;
            mPaint.setShader(new LinearGradient(0, mHeight, 0, bottomTop, mGradientColors,
                    mGradientPosition, Shader.TileMode.CLAMP));
            canvas.drawRect(0, bottomTop, mWidth, mHeight, mPaint);
        }

        if (leftTransWidth > 0) {
            mPaint.setShader(new LinearGradient(0, 0, leftTransWidth, 0, mGradientColors, mGradientPosition,
                    Shader.TileMode.CLAMP));
            canvas.drawRect(0, 0, leftTransWidth, mHeight, mPaint);
        }

        if (rightTransWidth > 0) {
            // 右侧左边缘位置
            float rightLeft = mWidth - rightTransWidth;
            rightLeft = rightLeft > 0 ? rightLeft : 0;

            mPaint.setShader(new LinearGradient(mWidth, 0, rightLeft, 0, mGradientColors, mGradientPosition,
                    Shader.TileMode.CLAMP));
            canvas.drawRect(rightLeft, 0, mWidth, mHeight, mPaint);
        }
        return drawChild;
    }


嗯嗯，参考你的实现方式，只要画笔是PorterDuff.Mode.DST_OUT这个mode就可以实现效果了，再次感谢答复，这个可以close了

**Comment by qinci** [comment]
恩  我测试了你给的代码，是有问题的
<img width="431" alt="截屏2021-01-13 下午9 20 15" src="https://user-images.githubusercontent.com/16683610/104457625-41846700-55e5-11eb-9f44-1abe3b5a87ad.png">



原来的执行效果：
<img width="427" alt="截屏2021-01-13 下午9 21 27" src="https://user-images.githubusercontent.com/16683610/104457666-4e08bf80-55e5-11eb-9e76-ff6a976781fd.png">
